### ISSUE TITLE
Readme updates

### ISSUE THREAD

**Issue by markwhiting** [iceLearn/Openlearnresearch#4]
From the feedback session today:
- [x] Solution section is not clear enough. Readers don’t necessarily understand what they’re getting into.
- [x] Town hall is really cool, perhaps include in the technical section too to tie together the technical community as well.
- [x] More details on contributing and code of conduct etc. (e.g. perhaps link to them and so forth)

**Comment by iceLearn** [comment]
- How to contribute is not clear - do you need to write to emails or is there a group to join like a google group
- A statement of where actually the project is currently, such as is it just started or developed upto which phase etc.
- Some graphics to show about the problem and solutions - boring with just words
- However, like the way it is flowing .. ;)

**Comment by markwhiting** [comment]
Cool. I think we can make some updates around these things. Would you like to take a first pass, or shall I?

**Comment by iceLearn** [comment]
Let the gents go first for a change ;) 
Its midnight here, tomorrow I will- 
add graphics
add issues

I would like you to set up the Discourse and let people join so we can start the community discussions

**Comment by markwhiting** [comment]
Cool.

**Comment by deHasara** [comment]
> How to contribute is not clear - do you need to write to emails or is there a group to join like a google group



-  So as a suggestion, how about starting a community discussion for the project using gitter?
https://gitter.im/Open-Learn-Research/openLearnResearch
So any problem regarding the project scope or contributions can be further discussed and it would be a forum open for anyone to join and collaborate

**Comment by iceLearn** [comment]
Good @deHasara . I added that in README file as to join

**Comment by markwhiting** [comment]
Closing this because I think it is all captured in the updates we've made.
